version: '3'
services:
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - 127.0.0.1:27017:27017
    volumes:
      - /data/messembed/mongo/data/db:/data/db
