version: '3'
services:
  messembed:
    build: .
    env_file: ./.env
    ports:
      - '127.0.0.1:3001:80'
    volumes:
      - /data/messembed/messembed/usr/src/app/node_modules:/usr/src/app/node_modules
    restart: unless-stopped
    depends_on:
      - mongo

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - 127.0.0.1:27017:27017
    volumes:
      - /data/messembed/mongo/data/db:/data/db
    restart: unless-stopped
